### ISSUE TITLE
sever.js

### ISSUE THREAD

**Issue by soggybag** [Jeffchiucp/reddit-nodeJS-clone#3]
Looks good needs some comments. Add comments to explain each section. Add a comment where you think something important would benefit from having a comment. 

Might be good to use a JavaScript Linter. Your code style is inconsistent. e.g. in some places you have

`{prop:value}`

and in others you have

`{ prop:value }`

Notice the spaces. The linter will point these out.

**Comment by Jeffchiucp** [comment]
Yes. Good catch. 
I forgot to run prettier in my project.
Will put down in my enhancement

**Comment by Jeffchiucp** [comment]
resolved issue
