### ISSUE TITLE
Create button...

### ISSUE THREAD

**Issue by soggybag** [Jeffchiucp/reddit-nodeJS-clone#6]
Create button is too close to the left edge. This needs some margin on the left. Really  I think the problem is how you are using Bootstrap. You have created an element that is class row. These only work they are inside of a container. See the examples here: 

http://getbootstrap.com/docs/4.0/layout/grid/

This button could use a better style. If you're already using Bootstrap you might as well use a Bootstrap button style. 

https://v4-alpha.getbootstrap.com/components/buttons/

you can apply these ideas to the button on other pages also.

**Comment by Jeffchiucp** [comment]
great feature request. 
I put down it down as enhancement from the user

**Comment by Jeffchiucp** [comment]
![screen shot 2017-10-13 at 2 25 18 pm](https://user-images.githubusercontent.com/10523517/31567059-78a7632a-b022-11e7-9226-cbdf3721cb63.png)

**Comment by Jeffchiucp** [comment]
will implement this bootstrap button style: 

<button type="button" class="btn btn-primary">Primary</button>
