### ISSUE TITLE
Comments could use some styles

### ISSUE THREAD

**Issue by soggybag** [Jeffchiucp/reddit-nodeJS-clone#8]
Comment could use some styles. The Think about using Boot strap styles for comments. 

The bigger issue is why not use Bootstrap styles everywhere? You have the library imported and are using it in a few places. Might as well use it everywhere!

**Comment by Jeffchiucp** [comment]
good feedback

**Comment by Jeffchiucp** [comment]
plan to run bootstrap through http://getbootstrap.com/docs/4.0/layout/grid/

**Comment by Jeffchiucp** [comment]
Need to get some additional help. https://github.com/soggybag/web-2-reddit-clone/tree/master/controllers

**Comment by Jeffchiucp** [comment]
this looks good to me now
